<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LichHocSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // --- Các bản ghi cũ ---
            [
                'lop_hoc_phan_id' => 8,
                'ngay' => '2025-10-20',
                'gio_bat_dau' => '07:30:00',
                'gio_ket_thuc' => '09:30:00',
                'phong_hoc_id' => 1,
                'hinh_thuc_buoi_hoc' => 'offline',
                'link_online' => null,
                'giang_vien_phu_trach' => 1,
                'ghi_chu' => 'Buổi học đầu tiên của lớp LHP001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'lop_hoc_phan_id' => 9,
                'ngay' => '2025-10-22',
                'gio_bat_dau' => '09:45:00',
                'gio_ket_thuc' => '11:45:00',
                'phong_hoc_id' => 2,
                'hinh_thuc_buoi_hoc' => 'offline',
                'link_online' => null,
                'giang_vien_phu_trach' => 1,
                'ghi_chu' => 'Buổi học thứ 2 của lớp LHP001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'lop_hoc_phan_id' => 10,
                'ngay' => '2025-10-23',
                'gio_bat_dau' => '13:30:00',
                'gio_ket_thuc' => '15:30:00',
                'phong_hoc_id' => 3,
                'hinh_thuc_buoi_hoc' => 'online',
                'link_online' => 'https://meet.smis.edu.vn/classroom10',
                'giang_vien_phu_trach' => 2,
                'ghi_chu' => 'Buổi học online qua Zoom',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'lop_hoc_phan_id' => 11,
                'ngay' => '2025-10-24',
                'gio_bat_dau' => '15:45:00',
                'gio_ket_thuc' => '17:45:00',
                'phong_hoc_id' => 4,
                'hinh_thuc_buoi_hoc' => 'offline',
                'link_online' => null,
                'giang_vien_phu_trach' => 3,
                'ghi_chu' => 'Buổi học đầu tiên của lớp LHP003',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'lop_hoc_phan_id' => 10,
                'ngay' => '2025-10-27',
                'gio_bat_dau' => '07:30:00',
                'gio_ket_thuc' => '09:30:00',
                'phong_hoc_id' => 4,
                'hinh_thuc_buoi_hoc' => 'hybrid',
                'link_online' => 'https://meet.smis.edu.vn/classroom10b',
                'giang_vien_phu_trach' => 3,
                'ghi_chu' => 'Buổi học kết hợp trực tiếp và online',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // --- 10 bản ghi mới ---
            [
                'lop_hoc_phan_id' => 11,
                'ngay' => '2025-10-28',
                'gio_bat_dau' => '08:00:00',
                'gio_ket_thuc' => '10:00:00',
                'phong_hoc_id' => 5,
                'hinh_thuc_buoi_hoc' => 'offline',
                'link_online' => null,
                'giang_vien_phu_trach' => 2,
                'ghi_chu' => 'Lập trình Java - buổi 1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lop_hoc_phan_id' => 11,
                'ngay' => '2025-10-30',
                'gio_bat_dau' => '08:00:00',
                'gio_ket_thuc' => '10:00:00',
                'phong_hoc_id' => 5,
                'hinh_thuc_buoi_hoc' => 'offline',
                'link_online' => null,
                'giang_vien_phu_trach' => 2,
                'ghi_chu' => 'Lập trình Java - buổi 2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lop_hoc_phan_id' => 8,
                'ngay' => '2025-10-29',
                'gio_bat_dau' => '13:00:00',
                'gio_ket_thuc' => '15:00:00',
                'phong_hoc_id' => 6,
                'hinh_thuc_buoi_hoc' => 'online',
                'link_online' => 'https://meet.smis.edu.vn/classroom13',
                'giang_vien_phu_trach' => 3,
                'ghi_chu' => 'Mạng máy tính - buổi online 1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lop_hoc_phan_id' => 9,
                'ngay' => '2025-11-01',
                'gio_bat_dau' => '13:00:00',
                'gio_ket_thuc' => '15:00:00',
                'phong_hoc_id' => 6,
                'hinh_thuc_buoi_hoc' => 'online',
                'link_online' => 'https://meet.smis.edu.vn/classroom13b',
                'giang_vien_phu_trach' => 3,
                'ghi_chu' => 'Mạng máy tính - buổi online 2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lop_hoc_phan_id' => 9,
                'ngay' => '2025-10-31',
                'gio_bat_dau' => '07:30:00',
                'gio_ket_thuc' => '09:30:00',
                'phong_hoc_id' => 7,
                'hinh_thuc_buoi_hoc' => 'offline',
                'link_online' => null,
                'giang_vien_phu_trach' => 1,
                'ghi_chu' => 'Cơ sở dữ liệu - buổi 1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lop_hoc_phan_id' => 10,
                'ngay' => '2025-11-03',
                'gio_bat_dau' => '07:30:00',
                'gio_ket_thuc' => '09:30:00',
                'phong_hoc_id' => 7,
                'hinh_thuc_buoi_hoc' => 'offline',
                'link_online' => null,
                'giang_vien_phu_trach' => 1,
                'ghi_chu' => 'Cơ sở dữ liệu - buổi 2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lop_hoc_phan_id' => 11,
                'ngay' => '2025-11-04',
                'gio_bat_dau' => '09:45:00',
                'gio_ket_thuc' => '11:45:00',
                'phong_hoc_id' => 8,
                'hinh_thuc_buoi_hoc' => 'hybrid',
                'link_online' => 'https://meet.smis.edu.vn/classroom15',
                'giang_vien_phu_trach' => 2,
                'ghi_chu' => 'Phân tích hệ thống - học kết hợp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lop_hoc_phan_id' => 10,
                'ngay' => '2025-11-05',
                'gio_bat_dau' => '13:30:00',
                'gio_ket_thuc' => '15:30:00',
                'phong_hoc_id' => 9,
                'hinh_thuc_buoi_hoc' => 'offline',
                'link_online' => null,
                'giang_vien_phu_trach' => 3,
                'ghi_chu' => 'Nhập môn AI - buổi 1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'lop_hoc_phan_id' => 11,
                'ngay' => '2025-11-07',
                'gio_bat_dau' => '13:30:00',
                'gio_ket_thuc' => '15:30:00',
                'phong_hoc_id' => 9,
                'hinh_thuc_buoi_hoc' => 'online',
                'link_online' => 'https://meet.smis.edu.vn/classroom16',
                'giang_vien_phu_trach' => 3,
                'ghi_chu' => 'Nhập môn AI - buổi online',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('lich_hoc')->insert($data);
    }
}
